export enum componentName {
  time = 'time',
  transform = 'transform',
  mouse = 'mouse',
  keyboard = 'keyboard',
  animation = 'animation',
  collider = 'collider',
  colliderQuadTree = 'colliderQuadTree',
  rigidBody = 'rigidBody',
  mouseInteraction = 'mouseInteraction',
  camera = 'camera',
  mesh = 'mesh',
  material = 'material',
  line2D = 'line2D',
}
